env:
  global:
  - AUTHOR_EMAIL=douglas@chippy.ch
  - REGISTRY_USERNAME=zuzak+travis_keycloak
  - REGISTRY=quay.io
  - secure: ZbrndCvMZbZf2sBo+PeIa7WXZAfHQVTNjQqmyi9Y0UQSQMhqNiDr6+bxhEaNfeLSDGfUChcjfrxRGu699WAcuYqKO3HOPa0qZttMXs+YeLyjTUkwnkF84FAy95Ta4R/XOeZs8EMZ1jz0ikrqup8htbii7g0QgN6msYtDVQxXJHXoHWHNPEC14selIqZUcDfQG8fGsZ/nxgsJSB9bBFPQflRb4hbkUDeBLVWQqLldMj5RZa/tgewGzpgeCBRzvWtyJyU9eRHaSVUc/P5ricxhW42E0UQOi0uoww+SIUDIjcsxgmPcLkvi2dfB3b1KixeAGhZ93QMNvzJMrF6fnRd2C6GgU0gYIB3HWsgSzCyrlokdSsSrr8LbvIdegCNzbbZiN5gcGEeY/wJfrCV152SDSS3qQp7LK0r6ARdSgBE00Qyfh0In+tXUJooNdxjO0GM/s2UZREbrW4X8NCU6Mo8TdIfhRS/rfeE5dAahWkuFPnQREW8YS/gPJWRzCOWoOEzhjDbAC/ZeN3CTSoPSyX9vOAw0JTpI9SkbcDV0cP3RPzw9H0EotgGPzdFHUFihYF+Bvfl5aseomdCYS4PYY2s4osEd2AVwzM103YcChxpZMaDqRvgsjoe9+jpOPgG0Ohj7aV1t2xxDT4QKDCt5n6btjKbLA2Pb9cxdMM8MIwPJrzs=
services:
- docker
language: go
go:
- 1.6
install:
- go get github.com/tools/godep
script:
- make test
- if [ -n "$TRAVIS_TAG" ]; then docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN}
  -e ${AUTHOR_EMAIL} ${REGISTRY}; VERSION=$TRAVIS_TAG make docker-release; fi
